"use client";
import {useEffect,useState} from "react";
import {ArrowRight,CalendarDays,ChevronLeft,ChevronRight,Clock3,Instagram,MapPin,Menu,Phone,Scissors,Sparkles,X} from "lucide-react";
import OwnerPanel from "../components/OwnerPanel";
const seed=[
{src:"https://lh3.googleusercontent.com/gps-cs-s/ANWiy9RDlWVUcADl-MS5mcAqjMALz1avgmWkuMhTkUPXNTP1J_HtHiSU1u9skAxV-KT6-y21GNlhFwW1FS3cJyS5wYbxiaV355eNm5xOAOyD6ItneQvi9-P4KT6y5R-GwWGm9l87Hu5j1cecdIX5=w397-h298-k-no",alt:"MomoHair salon"},
{src:"https://lh3.googleusercontent.com/gps-cs-s/ANWiy9QWHQt_CQXIHUCmVTavINDaKSsIn2-FscjTdlVIwjmCmRTknVhgRegrpdNEHB_8rDkBMmR4s3hwgM6UWMGUUZrPyqsvt7u0SeUh6h63t9BQ-XePjDSZ17_Uw4dS6yMWWJMGZE1dDUvL6BbI=w436-h298-k-no",alt:"MomoHair od zewnątrz"},
{src:"https://lh3.googleusercontent.com/gps-cs-s/ANWiy9RzDGeeNj8AC5eT3u3yWnOPZiOw-xJlRKCfFw_XVYUVnyKWn71irGae0lBmgLwae_EL2SpU8IJ_tTWzvYxk6KVm1LwX2FVUEuJ31pfziBx8DSPXdOAyJH9j7TesSa07CJvmCZlWYtWrzyth=w458-h298-k-no",alt:"MomoHair wnętrze"}];
const services=[["01","Strzyżenie damskie","Indywidualne cięcie, modelowanie i wykończenie."],["02","Strzyżenie męskie","Precyzyjne cięcie dopasowane do stylu i kształtu twarzy."],["03","Koloryzacja","Odświeżenie koloru i metamorfozy dopasowane do Ciebie."],["04","Stylizacja","Włosy przygotowane na co dzień, ważne wyjście lub sesję."]];
const reviews=[["Szymon Rybarczyk","Pierwszy raz byłem dzisiaj w tym salonie. Bardzo miła obsługa, podejście do klienta na najwyższym poziomie, staranność i szczery uśmiech. Polecam."],["Joanna Kruszyńska","Opinia klientki z Google Maps. W opinii zgłosiła zastrzeżenia dotyczące obsługi i efektu strzyżenia."],["D W","Opinia klienta z Google Maps. W opinii zgłoszono zastrzeżenia dotyczące obsługi i warunków w salonie."]];
export default function Home(){const[menu,setMenu]=useState(false);const[gallery,setGallery]=useState(seed);const[light,setLight]=useState<number|null>(null);const[owner,setOwner]=useState(false);useEffect(()=>{const raw=localStorage.getItem("momohair-gallery");if(raw)try{setGallery(JSON.parse(raw))}catch{}},[]);function save(g:any[]){setGallery(g);localStorage.setItem("momohair-gallery",JSON.stringify(g))}return <main>
<header className="nav"><a className="logo" href="#">Momo<span>Hair</span></a><nav className={menu?"open":""}>{["O salonie","Usługi","Galeria","Opinie","Kontakt"].map((x,i)=><a key={x} href={["#about","#services","#gallery","#reviews","#contact"][i]} onClick={()=>setMenu(false)}>{x}</a>)}<a className="nav-book" href="https://booksy.com/pl-pl/rwg/333354_momo-hair_fryzjer_22045_lebork" target="_blank">Zarezerwuj wizytę <ArrowRight size={16}/></a></nav><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Menu"><Menu/></button></header>
<section className="hero"><div className="hero-copy"><div className="eyebrow"><span></span> SALON FRYZJERSKI · LĘBORK</div><h1>Twoje włosy.<br/><em>Twój styl.</em></h1><p>Nowoczesne cięcia, kolor i stylizacja w miejscu, w którym liczy się efekt i dobre samopoczucie.</p><div className="hero-actions"><a className="btn dark" href="https://booksy.com/pl-pl/rwg/333354_momo-hair_fryzjer_22045_lebork" target="_blank">Umów wizytę <ArrowRight size={18}/></a><a className="text-link" href="#gallery">Zobacz salon <ArrowRight size={17}/></a></div></div><div className="hero-card"><img src={gallery[0]?.src} alt="MomoHair salon"/><div className="hero-badge"><Sparkles size={18}/><span>STYL<br/><b>BEZ KOMPROMISÓW</b></span></div></div></section>
<section id="about" className="about section"><div className="section-label">01 / O SALONIE</div><div className="about-grid"><h2>Miejsce na <em>dobrą zmianę.</em></h2><div><p className="lead">MomoHair to salon fryzjerski przy Mostnika 1 w Lęborku. Stawiamy na świeże podejście do fryzjerstwa, dopracowany detal i atmosferę, do której chce się wracać.</p><p>Wpadnij na szybką zmianę albo zaplanuj pełną metamorfozę. Każdą wizytę zaczynamy od rozmowy, żeby efekt pasował do Ciebie, a nie odwrotnie.</p></div></div></section>
<section id="services" className="services section"><div className="section-head"><div><div className="section-label">02 / USŁUGI</div><h2>Fryzjerstwo <em>po Twojemu.</em></h2></div><p>Zakres usług dopasowany do codziennych potrzeb i większych zmian.</p></div><div className="service-grid">{services.map(s=><article className="service" key={s[0]}><span>{s[0]}</span><Scissors size={21}/><h3>{s[1]}</h3><p>{s[2]}</p><a href="https://booksy.com/pl-pl/rwg/333354_momo-hair_fryzjer_22045_lebork" target="_blank">Umów <ArrowRight size={15}/></a></article>)}</div></section>
<section id="gallery" className="gallery section"><div className="section-head"><div><div className="section-label">03 / GALERIA</div><h2>Zobacz <em>MomoHair.</em></h2></div><span className="gallery-count">{gallery.length} zdjęcia</span></div><div className="masonry">{gallery.map((im,i)=><button className={"photo p"+(i%4)} key={im.src+i} onClick={()=>setLight(i)}><img src={im.src} alt={im.alt||"MomoHair"} loading="lazy"/></button>)}</div></section>
<section id="reviews" className="reviews section"><div className="section-label">04 / OPINIE</div><div className="reviews-top"><h2>Głos <em>klientów.</em></h2><div className="rating"><strong>4,7</strong><div><div className="stars">★★★★★</div><small>23 opinie w Google</small></div></div></div><div className="review-grid">{reviews.map(r=><article key={r[0]}><div className="stars">★★★★★</div><p>„{r[1]}”</p><b>{r[0]}</b></article>)}</div></section>
<section id="contact" className="contact section"><div className="contact-card"><div><div className="section-label">05 / KONTAKT</div><h2>Wpadnij do<br/><em>MomoHair.</em></h2><p>Mostnika 1<br/>84-300 Lębork</p><a className="phone" href="tel:+48518160818"><Phone size={18}/>518 160 818</a></div><div className="hours"><h3>Godziny otwarcia</h3>{["Poniedziałek","Wtorek","Środa","Czwartek","Piątek","Sobota","Niedziela"].map(d=><div key={d}><span>{d}</span><b>Sprawdź aktualne</b></div>)}</div><div className="map"><iframe title="MomoHair na mapie" src="https://www.google.com/maps?q=Mostnika+1,+84-300+L%C4%99bork&output=embed" loading="lazy"/><a href="https://www.google.com/maps/dir/?api=1&destination=Mostnika+1,+84-300+L%C4%99bork" target="_blank" className="route">Wyznacz trasę <ArrowRight size={17}/></a></div></div></section>
<footer><div><a className="logo" href="#">Momo<span>Hair</span></a><p>Salon fryzjerski · Lębork</p></div><div className="footer-links"><a href="https://booksy.com/pl-pl/rwg/333354_momo-hair_fryzjer_22045_lebork" target="_blank">Rezerwacja online</a><a href="tel:+48518160818">518 160 818</a><button onClick={()=>setOwner(true)}>Panel właściciela</button></div><small>© 2026 MomoHair. Wszystkie prawa zastrzeżone.</small></footer>
{light!==null&&<div className="lightbox" onClick={()=>setLight(null)}><button className="close" onClick={()=>setLight(null)}><X/></button><button className="lb prev" onClick={e=>{e.stopPropagation();setLight((light-1+gallery.length)%gallery.length)}}><ChevronLeft/></button><img src={gallery[light].src} alt={gallery[light].alt||"MomoHair"}/><button className="lb next" onClick={e=>{e.stopPropagation();setLight((light+1)%gallery.length)}}><ChevronRight/></button></div>}
<OwnerPanel open={owner} onClose={()=>setOwner(false)} gallery={gallery} onSave={save}/></main>}
